name: Publish Python Package to S3

on:
  push:
    branches:
      - main  # Or specify the branch you want to trigger the deployment

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  dist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools_scm

      - name: Extract Version from Tag
        id: extract_version
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            VERSION="0.0.0.dev"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build package
        run: |
          sed -i "s|^version = .*|version = ${VERSION}|" setup.cfg
          python -m build

      #      - name: Attach artifact to build
      #        uses: actions/upload-artifact@v4
      #        with:
      #          name: dist
      #          path: dist

      - name: Upload to S3
        env:
          AWS_REGION: eu-west-1
        run: |
          PACKAGE_NAME=$(python setup.py --name)
          S3_BUCKET="s3://downloads.glowbuzzer.com/releases/${PACKAGE_NAME}/"

          # Upload the .tar.gz and .whl files to S3
          aws s3 cp dist/ ${S3_BUCKET} --recursive

          # Generate index.html for the directory
          INDEX_FILE=$(mktemp)
          echo "<html><body><h1>Index of ${PACKAGE_NAME}</h1><ul>" > $INDEX_FILE
          aws s3 ls ${S3_BUCKET} | awk '{print $4}' | while read -r FILE; do
            echo "<li><a href=\"$FILE\">$FILE</a></li>" >> $INDEX_FILE
          done
          echo "</ul></body></html>" >> $INDEX_FILE

          # Upload index.html to S3
          aws s3 cp $INDEX_FILE ${S3_BUCKET}index.html --content-type "text/html"
