name: Release Please

on:
  push:
    tags:
      - v*b*

env:
  TWINE_USERNAME: __token__
  TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools_scm twine

      - name: Update version in pyproject.toml using github ref
        run: |
          sed -i "s/version = .*/version = \"${GITHUB_REF#refs/tags/v}\"/g" pyproject.toml

      - name: Build package
        run: |
          python -m build

      - name: Attach artifacts
        uses: actions/upload-artifact@v4
        with:
          path: dist
          name: dist

#      - name: Publish package
#        run: |
#          python -m twine upload dist/*
